package com.sl.mycycle.domain.model

enum class CycleNotice {
    CYCLE_STAGE_NOT_SET,
    FIRST_YEAR_CHANGES_ARE_COMMON,
    EARLY_YEARS_CHANGES_ARE_COMMON,
    LONG_TERM_UNEVEN,
    CHANGING_WITH_AGE,
    PERIODS_STOPPED,
    THREE_MONTH_GAP,
    LONG_UNEXPLAINED_GAP,
    BLEEDING_AFTER_YEAR_GAP,
    LONG_BLEEDING,
    OUTSIDE_COMMON_RANGE
}
